version: '3'

services:

  serverpostgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - ./database-volume:/var/lib/postgresql/data
      
  serverpgadmin:
    image: dpage/pgadmin4
    environment:

      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - serverpostgres

